# Generated by Django 3.1 on 2020-08-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_body', models.TextField()),
                ('event_added', models.DateTimeField(auto_now_add=True)),
                ('event_removed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tradlos_eventmessage',
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_added', models.DateTimeField(auto_now_add=True)),
                ('message_removed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tradlos_sysmessage',
            },
        ),
    ]
