# Generated by Django 3.1 on 2020-08-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.CharField(choices=[('PB', 'Public'), ('RS', 'Restricted'), ('BT', 'Beta')], default='BT', max_length=2)),
                ('game_name', models.CharField(max_length=40)),
                ('game_url_root', models.CharField(max_length=24)),
                ('game_removed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tradlos_game',
            },
        ),
    ]
